import express from "express";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI } from "@google/genai";
import dotenv from "dotenv";

dotenv.config();

async function startServer() {
  const app = express();
  const PORT = 3000;

  app.use(express.json({ limit: '50mb' }));

  // Gemini API Route
  app.post("/api/process-image", async (req, res) => {
    try {
      const { base64Image, mimeType, style } = req.body;
      
      const apiKey = process.env.GEMINI_API_KEY;
      if (!apiKey) {
        return res.status(500).json({ error: "GEMINI_API_KEY is not configured on the server." });
      }

      const ai = new GoogleGenAI({ apiKey });
      const prompt = `
        You are a professional e-commerce product photographer and editor.
        Task: Remove the background of the main product in this image and replace it with a new background.
        
        Requirements:
        1. Detect the main product accurately.
        2. Remove the existing background completely.
        3. Generate a new background in "${style}" style.
        4. The new background should complement the product's colors and theme.
        5. Ensure professional studio-quality lighting and shadows that make the product pop.
        6. Keep the product at its original scale but centered.
        7. Output ONLY the edited image.
        
        Style Guide:
        - minimal: Clean, solid or very subtle gradient background, often white or light gray.
        - luxury: Premium textures like marble, silk, or dark elegant wood with dramatic lighting.
        - tech: Modern, sleek, maybe some subtle glow or geometric patterns, cool tones.
        - soft: Pastel colors, soft shadows, warm inviting atmosphere.
        - premium: High-end studio look with professional depth of field and clean surfaces.
        - outdoor: Natural lighting, blurred nature or urban background that fits the product.
        - studio: Classic professional product photography setup with softbox lighting.
      `;

      const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
          parts: [
            {
              inlineData: {
                data: base64Image, // Already stripped of prefix if needed, or handle here
                mimeType: mimeType,
              },
            },
            {
              text: prompt,
            },
          ],
        },
      });

      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
          return res.json({ image: `data:image/png;base64,${part.inlineData.data}` });
        }
      }

      res.status(500).json({ error: "No image generated by AI." });
    } catch (error: any) {
      console.error("Server Error:", error);
      res.status(500).json({ error: error.message || "Internal Server Error" });
    }
  });

  // Vite middleware for development
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    app.use(express.static("dist"));
    app.get("*", (req, res) => {
      res.sendFile("dist/index.html", { root: "." });
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
